test(SSO/saml2): skip test - it does not work without build/webpack
Exception: You need to run webpack-dev-server in dev mode!
858/usr/share/tine20/Tinebase/Frontend/Http/SinglePageApplication.php:117
859/usr/share/tine20/Tinebase/Frontend/Http/SinglePageApplication.php:157
860/usr/share/tine20/Tinebase/Frontend/Http/SinglePageApplication.php:47
861/usr/share/tine20/SSO/Controller.php:602
862/usr/share/tine20/SSO/Controller.php:544
863/usr/share/tests/tine20/SSO/PublicAPITest.php:97