integer fields are not allowed in query filter
... because pgsql is picky here. to allow them, we
would need a typecast in the query

Zend_Db_Statement_Exception: SQLSTATE[42883]: Undefined function: 7
ERROR:  operator does not exist: integer ~~* unknown
LINE 1: ...is_deleted" = 0) AND (("sales_customers"."number" iLIKE('%wo..

Change-Id: I1051bad84f88fba0604d59370f7fd8450ca80d08
Reviewed-on: http://gerrit.tine20.com/customers/2883
Reviewed-by: Philipp Schüle <p.schuele@metaways.de>
Tested-by: Philipp Schüle <p.schuele@metaways.de>