test(TInebase/Cli): skip sentry test due to composer ci issue
Error: Class 'PackageVersions\Versions' not found
/usr/share/tine20/vendor/jean85/pretty-package-versions/src/PrettyVersions.php:13
/usr/share/tine20/vendor/sentry/sentry/src/ClientBuilder.php:79
/usr/share/tine20/vendor/sentry/sentry/src/ClientBuilder.php:87
/usr/share/tine20/vendor/sentry/sentry/src/functions.php:17
/usr/share/tine20/Tinebase/Core.php:2436
/usr/share/tests/tine20/Tinebase/Frontend/CliTest.php:716