fix(Tinebase/Controller): add missing 'new'
we would get this error otherwise:
Error: Call to undefined function Tinebase_Exception()

Change-Id: I9a91d71d5a6660c91eb51090187d3a677e11f947
Reviewed-on: http://gerrit.tine20.com/customers/17789
Tested-by: Jenkins CI (http://ci.tine20.com/) <tine20-jenkins@metaways.de>
Reviewed-by: Philipp Schüle <p.schuele@metaways.de>