tests(Felamimail/Import): don't delete definition
... because of:

Zend_Db_Statement_Exception: SQLSTATE[23000]: Integrity constraint violation:
 1062 Duplicate entry 'Addressbook_Model_Contact-testFelamimailImportImap-import-2022-0
/usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:235
/usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php:303
/usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php:480
/usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:238
/usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php:636
/usr/share/tine20/Tinebase/Backend/Sql/Abstract.php:1371
/usr/share/tine20/Tinebase/Controller/Record/Abstract.php:2325
/usr/share/tine20/Tinebase/Controller/Record/Abstract.php:2138
/usr/share/tests/tine20/Felamimail/Import/ImapTest.php:53